[build]
  command = "npm run build && pip install -r flask/requirements.txt"
  functions = "flask" 
  publish = "frontend/build"
  image = "python:3.8"

[[redirects]]
  from = "/recommend/*"
  to = "http://localhost:5000/:splat"
  status = 200
  force = true

[context.production]
  command = "python backend.py"
